# Generated by Django 4.2.5 on 2023-09-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('y360', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='membersCount',
            field=models.IntegerField(default=0, help_text='count of members'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groups',
            name='membersCount',
            field=models.IntegerField(default=0, help_text='count of members'),
            preserve_default=False,
        ),
    ]
