# Generated by Django 4.2.5 on 2023-09-08 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('y360', '0002_departments_memberscount_groups_memberscount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groups_staff',
            old_name='groupID',
            new_name='groupId',
        ),
        migrations.AddField(
            model_name='departments',
            name='label',
            field=models.CharField(help_text='email part before @', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='groups',
            name='label',
            field=models.CharField(help_text='email part before @', max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Groups_Hierarchy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('childId', models.CharField(max_length=200)),
                ('parentId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='y360.groups')),
            ],
        ),
    ]
