# Generated by Django 4.2.5 on 2023-09-08 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('y360', '0003_rename_groupid_groups_staff_groupid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='parentId',
        ),
    ]
