# Generated by Django 4.2.5 on 2023-09-09 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('y360', '0004_remove_groups_parentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups_hierarchy',
            name='childId',
            field=models.IntegerField(help_text='id of a group'),
        ),
        migrations.AlterField(
            model_name='groups_hierarchy',
            name='parentId',
            field=models.ForeignKey(help_text='id of a parent group', null=True, on_delete=django.db.models.deletion.SET_NULL, to='y360.groups'),
        ),
        migrations.CreateModel(
            name='Groups_Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberId', models.IntegerField(help_text="member's ID")),
                ('memberType', models.CharField(help_text='group or user', max_length=100)),
                ('groupId', models.ForeignKey(help_text='group ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='y360.groups')),
            ],
        ),
    ]
