# Generated by Django 4.2.5 on 2023-09-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('y360', '0006_domains'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='description',
            field=models.CharField(help_text='department description', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='groups',
            name='description',
            field=models.CharField(help_text='department description', max_length=200, null=True),
        ),
    ]
