# Generated by Django 4.2.4 on 2023-12-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('y360', '0008_alter_groups_hierarchy_parentid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='img',
            field=models.CharField(help_text='Ico ID from yandex', max_length=100),
        ),
    ]
